"""High-contrast dual-stroke contour rendering for accessibility research."""

from cs2_vision_access.renderer.draw import (
    OutlineRenderer,
    current_frame_masks,
    draw_styled_polylines,
)
from cs2_vision_access.renderer.patterns import pattern_polyline_segments
from cs2_vision_access.renderer.roles import (
    ROLE_CATALOG_SCHEMA_VERSION,
    ROLE_MARKERS,
    RoleTreatment,
    TreatmentCatalog,
    load_treatment_catalog,
    treatment_catalog_from_mapping,
)
from cs2_vision_access.renderer.style import (
    AREA_WIDTH_SCALE_MAX,
    AREA_WIDTH_SCALE_MIN,
    DEFAULT_DASH_PERIOD_PX,
    DEFAULT_HALO_BLUR,
    DRAW_COORDINATE_SCALE,
    DRAW_COORDINATE_SHIFT,
    FILL_MODES,
    MINIMUM_STROKE_CONTRAST,
    OUTLINE_KERNELS,
    OUTLINE_PRESET_DESCRIPTIONS,
    OUTLINE_PRESETS,
    REFERENCE_AREA_FRACTION,
    REFERENCE_FRAME_HEIGHT,
    STROKE_PATTERNS,
    OutlineStyle,
    RenderDiagnostics,
    contrast_ratio,
    effective_dash_period,
    effective_instance_line_widths,
    effective_line_widths,
    get_outline_preset,
    parse_hex_bgr,
)
from cs2_vision_access.renderer.supervision import (
    SupervisionAnnotator,
    SupervisionAnnotatorConfig,
    SupervisionBridgeError,
    detections_to_instance_masks,
    instance_masks_to_detections,
)

__all__ = [
    "AREA_WIDTH_SCALE_MAX",
    "AREA_WIDTH_SCALE_MIN",
    "DEFAULT_DASH_PERIOD_PX",
    "DEFAULT_HALO_BLUR",
    "DRAW_COORDINATE_SCALE",
    "DRAW_COORDINATE_SHIFT",
    "FILL_MODES",
    "MINIMUM_STROKE_CONTRAST",
    "OUTLINE_KERNELS",
    "OUTLINE_PRESET_DESCRIPTIONS",
    "OUTLINE_PRESETS",
    "OutlineRenderer",
    "OutlineStyle",
    "REFERENCE_AREA_FRACTION",
    "REFERENCE_FRAME_HEIGHT",
    "ROLE_CATALOG_SCHEMA_VERSION",
    "ROLE_MARKERS",
    "RenderDiagnostics",
    "RoleTreatment",
    "STROKE_PATTERNS",
    "SupervisionAnnotator",
    "SupervisionAnnotatorConfig",
    "SupervisionBridgeError",
    "TreatmentCatalog",
    "contrast_ratio",
    "detections_to_instance_masks",
    "instance_masks_to_detections",
    "current_frame_masks",
    "draw_styled_polylines",
    "effective_dash_period",
    "effective_instance_line_widths",
    "effective_line_widths",
    "get_outline_preset",
    "load_treatment_catalog",
    "parse_hex_bgr",
    "pattern_polyline_segments",
    "treatment_catalog_from_mapping",
]
