# Simulation replay must be reproducible across fresh configure runs.  These
# values are intentionally stable; real-adapter experiments own any host or
# build-specific material at their outer boundary.
set(XOR_KEY_SEED 0x2A5D1C3E)
set(TIMING_SALT 0x4B7F19D2)
set(CLASS_SEED 0x1A2B3C4D)
set(API_SALT 0x5E6F7081)
set(COMPILE_SALT 0x13579BDF)
set(SECTION_SEED 0x2468ACE0)
set(GUID_SEED 0x10293847)
set(SURFACE_SEED 0x55667788)

option(LR_BUILD_ID "Build identifier for watermarking" 0)
option(LAB_ALLOW_HIJACK_PROXY "Simulate hijack/proxy acquisition" OFF)
option(LAB_ALLOW_KERNEL "Simulate kernel driver (T2)" OFF)
option(LAB_ALLOW_HV "Simulate hypervisor (T3)" OFF)
option(LAB_ALLOW_DMA "Simulate DMA (T4)" OFF)
option(LAB_ALLOW_BAND4 "Simulate band-4 overlay" OFF)
option(LAB_ALLOW_SEDEBUG "Simulate SeDebugPrivilege use" OFF)
option(LR_ENABLE_VEH "Enable VEH anti-debug handler (kernel-visible)" OFF)
option(LR_BUILD_PROTOS "Build per-tier proto demos" ON)
option(LR_BUILD_DUELS "Build per-tier duel demos" ON)
option(LR_BUILD_STRATEGY_LAB "Build strategy_lab catalog runner" ON)

option(LR_ENABLE_REAL_RPM "Build real Windows ReadProcessMemory backend" OFF)
option(LR_ENABLE_REAL_SYSCALL "Build real direct syscall backend" OFF)
option(LR_ENABLE_REAL_KERNEL "Build real kernel/BYOVD backend" OFF)
option(LR_ENABLE_REAL_VMX "Build real Intel VT-x hypervisor backend" OFF)
option(LR_ENABLE_REAL_DMA "Build real DMA/PCIe backend" OFF)
option(LR_ENABLE_REAL_SMM "Build real SMM/firmware backend" OFF)
option(LR_ENABLE_REAL_GPU "Build real GPU rendering/compute backends" OFF)
option(LR_ENABLE_REAL_NET "Build real networking/C2 backends" OFF)
option(LR_ENABLE_REAL_UEFI "Build UEFI firmware backend" OFF)
option(LR_ENABLE_REAL_LINUX "Build Linux real backend and host stubs" OFF)
option(LR_ENABLE_REAL_ALL "Enable ALL real backends (use with care)" OFF)
option(LR_ENABLE_SHELLCODE_INJECTION "Build the isolated Windows x64 shellcode research adapter" OFF)

if(LR_ENABLE_REAL_ALL)
  foreach(opt RPM SYSCALL KERNEL VMX DMA SMM GPU NET UEFI LINUX)
    set(LR_ENABLE_REAL_${opt} ON)
  endforeach()
endif()

if(LR_BUILD_ID)
  target_compile_definitions(lr_build_options INTERFACE BUILD_ID=${LR_BUILD_ID})
endif()
foreach(opt LAB_ALLOW_HIJACK_PROXY LAB_ALLOW_KERNEL LAB_ALLOW_HV LAB_ALLOW_DMA LAB_ALLOW_BAND4 LAB_ALLOW_SEDEBUG LR_ENABLE_VEH)
  if(${opt})
    target_compile_definitions(lr_build_options INTERFACE ${opt}=1)
  endif()
endforeach()

set(LR_REAL_ENABLED OFF)
foreach(opt RPM SYSCALL KERNEL VMX DMA SMM GPU NET UEFI LINUX)
  if(LR_ENABLE_REAL_${opt})
    set(LR_REAL_ENABLED ON)
    target_compile_definitions(lr_build_options INTERFACE LR_HAS_REAL_${opt}=1)
  endif()
endforeach()
if(APPLE AND LR_REAL_ENABLED)
  message(FATAL_ERROR "Real backend features are unsupported on Apple. Leave LR_ENABLE_REAL_* options OFF.")
endif()
if(LR_ENABLE_SHELLCODE_INJECTION)
  if(NOT LR_ENABLE_REAL_SYSCALL)
    message(FATAL_ERROR "LR_ENABLE_SHELLCODE_INJECTION requires LR_ENABLE_REAL_SYSCALL=ON.")
  endif()
  if(NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "LR_ENABLE_SHELLCODE_INJECTION requires a 64-bit Windows lab host.")
  endif()
  target_compile_definitions(lr_build_options INTERFACE LR_HAS_REAL_SHELLCODE=1)
else()
  target_compile_definitions(lr_build_options INTERFACE LR_HAS_REAL_SHELLCODE=0)
endif()
if(WIN32)
  target_compile_definitions(lr_build_options INTERFACE LR_PLATFORM_WINDOWS=1 LR_PLATFORM_LINUX=0)
  set(REAL_PLATFORM_LIBS "")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  target_compile_definitions(lr_build_options INTERFACE LR_PLATFORM_WINDOWS=0 LR_PLATFORM_LINUX=1)
  set(REAL_PLATFORM_LIBS pthread dl rt)
else()
  target_compile_definitions(lr_build_options INTERFACE LR_PLATFORM_WINDOWS=0 LR_PLATFORM_LINUX=0)
endif()

message(STATUS "Deterministic simulation seed: ${XOR_KEY_SEED} BUILD_ID:${LR_BUILD_ID}")
configure_file("${RADAR_SOURCE_DIR}/cmake/build_keys.hpp.in" "${RADAR_GENERATED_DIR}/build_keys.hpp" @ONLY)

if(MSVC)
  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2 /Ob2 /DNDEBUG /GS /GR-")
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DYNAMICBASE /guard:cf /HIGHENTROPYVA /NXCOMPAT /PDBSTRIPPED /PDBALTPATH:NUL /CETCOMPAT /MANIFEST:NO")
else()
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -fvisibility=hidden -ffunction-sections -fdata-sections")
  if(APPLE)
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -Wl,-dead_strip")
  else()
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -Wl,--gc-sections")
  endif()
endif()
