include("${CMAKE_CURRENT_LIST_DIR}/RealSources.cmake")

if(LR_REAL_ENABLED)
  # Each real option owns a narrow static library.  The common target contains
  # only platform-neutral adapter primitives, never a bag of all real sources.
  function(lr_real target)
    lr_library(${target} ${ARGN})
    target_include_directories(${target} PUBLIC "${RADAR_SOURCE_DIR}/adapters")
  endfunction()

  lr_real(ac_real_core ${LR_REAL_CORE_SOURCES})
  target_link_libraries(ac_real_core PUBLIC ac_common ${REAL_PLATFORM_LIBS})
  set(LR_REAL_ENABLED_TARGETS ac_real_core)

  if(LR_ENABLE_REAL_RPM)
    lr_real(ac_real_rpm ${LR_REAL_RPM_SOURCES})
    target_link_libraries(ac_real_rpm PUBLIC ac_real_core ac_common)
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_rpm)
  endif()
  if(LR_ENABLE_REAL_SYSCALL)
    lr_real(ac_real_syscall ${LR_REAL_SYSCALL_SOURCES})
    target_link_libraries(ac_real_syscall PUBLIC ac_real_core)
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_syscall)
  endif()
  if(LR_ENABLE_REAL_KERNEL)
    lr_real(ac_real_kernel ${LR_REAL_kernel_SOURCES})
    target_link_libraries(ac_real_kernel PUBLIC ac_real_core ac_common)
    if(WIN32)
      target_link_libraries(ac_real_kernel PUBLIC psapi advapi32)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_kernel)
  endif()
  if(LR_ENABLE_REAL_VMX)
    lr_real(ac_real_vmx ${LR_REAL_vmx_SOURCES})
    target_link_libraries(ac_real_vmx PUBLIC ac_real_core)
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_vmx)
  endif()
  if(LR_ENABLE_REAL_DMA)
    lr_real(ac_real_dma ${LR_REAL_dma_SOURCES})
    target_link_libraries(ac_real_dma PUBLIC ac_real_core ac_common)
    if(WIN32)
      target_link_libraries(ac_real_dma PUBLIC setupapi cfgmgr32 advapi32)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_dma)
  endif()
  if(LR_ENABLE_REAL_GPU)
    lr_real(ac_real_gpu ${LR_REAL_gpu_SOURCES})
    target_link_libraries(ac_real_gpu PUBLIC ac_real_core)
    if(WIN32)
      target_link_libraries(ac_real_gpu PUBLIC d3d11 dxgi dxguid)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_gpu)
  endif()
  if(LR_ENABLE_REAL_NET)
    lr_real(ac_real_net ${LR_REAL_net_SOURCES})
    target_link_libraries(ac_real_net PUBLIC ac_real_core)
    if(WIN32)
      target_link_libraries(ac_real_net PUBLIC ws2_32 winhttp bcrypt crypt32)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_net)
  endif()
  if(LR_ENABLE_REAL_SMM)
    lr_real(ac_real_smm ${LR_REAL_smm_SOURCES})
    target_link_libraries(ac_real_smm PUBLIC ac_real_core)
    if(WIN32)
      target_link_libraries(ac_real_smm PUBLIC advapi32)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_smm)
  endif()
  if(LR_ENABLE_REAL_UEFI)
    lr_real(ac_real_uefi ${LR_REAL_uefi_SOURCES})
    target_link_libraries(ac_real_uefi PUBLIC ac_real_core)
    if(WIN32)
      target_link_libraries(ac_real_uefi PUBLIC setupapi advapi32)
    endif()
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_uefi)
  endif()
  if(LR_ENABLE_REAL_LINUX AND EXISTS "${RADAR_SOURCE_DIR}/adapters/real/linux/CMakeLists.txt")
    add_subdirectory("${RADAR_SOURCE_DIR}/adapters/real/linux" "${CMAKE_CURRENT_BINARY_DIR}/ac_linux")
    list(APPEND LR_REAL_ENABLED_TARGETS ac_linux)
  endif()
  if(LR_ENABLE_SHELLCODE_INJECTION)
    lr_real(ac_real_shellcode ${LR_REAL_SHELLCODE_SOURCES})
    target_include_directories(ac_real_shellcode PRIVATE "${RADAR_GENERATED_DIR}")
    target_link_libraries(ac_real_shellcode PUBLIC ac_real_syscall)
    list(APPEND LR_REAL_ENABLED_TARGETS ac_real_shellcode)
  endif()

  add_library(ac_real INTERFACE)
  target_link_libraries(ac_real INTERFACE ${LR_REAL_ENABLED_TARGETS})
  string(JOIN "\n" _real_manifest ${LR_REAL_ENABLED_TARGETS})
  file(WRITE "${CMAKE_BINARY_DIR}/radar-real-targets.txt" "${_real_manifest}\n")
  set(LR_HAS_REAL_PLATFORM 1)
else()
  file(WRITE "${CMAKE_BINARY_DIR}/radar-real-targets.txt" "simulation-only\n")
  set(LR_HAS_REAL_PLATFORM 0)
endif()
target_compile_definitions(lr_build_options INTERFACE LR_HAS_REAL_PLATFORM=${LR_HAS_REAL_PLATFORM})
