"""Documented compatibility facade for config-driven auto training."""

from cs2_vision_access.workflows.training.auto import (
    EXIT_FAIL,
    EXIT_HUMAN_GATE,
    EXIT_OK,
    STAGE_ORDER,
    AutoTrainConfig,
    AutoTrainConfigError,
    AutoTrainError,
    AutoTrainResult,
    AutoTrainStageError,
    HumanGateBlocked,
    RunPaths,
    StageState,
    append_event,
    build_run_paths,
    load_config,
    materialize_flat_cloud_bundle,
    run_auto_train,
)

__all__ = [
    "EXIT_FAIL",
    "EXIT_HUMAN_GATE",
    "EXIT_OK",
    "STAGE_ORDER",
    "AutoTrainConfig",
    "AutoTrainConfigError",
    "AutoTrainError",
    "AutoTrainResult",
    "AutoTrainStageError",
    "HumanGateBlocked",
    "RunPaths",
    "StageState",
    "append_event",
    "build_run_paths",
    "load_config",
    "materialize_flat_cloud_bundle",
    "run_auto_train",
]
