from typing import Any

class YOLO:
    def __init__(self, model: str | Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def predict(self, *args: Any, **kwargs: Any) -> Any: ...
    def train(self, *args: Any, **kwargs: Any) -> Any: ...
    def export(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_callback(self, event: str, callback: Any) -> None: ...

class SAM:
    def __init__(self, model: str | Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
